### ISSUE TITLE
Bump version to include 8 bit support?

### ISSUE THREAD

**Issue by FR86** [AuburnSounds/gamut#22]
Hey, I stumbled over this awesome library, thanks a lot for writing it!
Would you mind tagging a new version so that dub users like me can have 8 bit support for png's? I've seen #21, so I understand if the answer is no for now...

**Comment by p0nce** [comment]
Hello, bumped gamut v0.0.8
#21 is no big deal, since DMD with optimization often fails, it's not particularly surprising for a D library.
It is heavily recommended to use LDC or GDC for correct codegen with optimization!
