### ISSUE TITLE
Please provide a way to gracefully fail for corrupt jpegs

### ISSUE THREAD

**Issue by gizmomogwai** [AuburnSounds/gamut#46]
First of all thanks for this excellent library. I was able to replace [imagefmt](https://code.dlang.org/packages/imagefmt) quickly with your library (which supports more imageformats and variants.

While testing I encountered `assert(false` calls in stop_decoding (e.g. trying to load a jpeg from an empty file).
It would be great if the error handling could be done on application level and the load in this case would return an invalid image.

I created a local patch for that (by removing the assert and replacing all calls to stop_decoding with stop_decoding and a return, but I am not sure that this is the best way.

**Comment by p0nce** [comment]
Hello,

Normally all failed loading should fail with `isError`, so this is a bug in the decoder if an empty file asserted (which is an input error, not a logic error).

**Comment by p0nce** [comment]
JPEG loader should now gracefully handle bad input, though only fuzzing will tell. Probably leaks a bit of memory on bad input.
Use 2.1.2+

**Comment by p0nce** [comment]
This is 2bc035c4b4384e460ffad7e9fa32b24918648e0d

**Comment by gizmomogwai** [comment]
Wow .. that was fast, will give it a try!

**Comment by gizmomogwai** [comment]
Works for my usecase (empty jpg), thanks a lot!

**Comment by gizmomogwai** [comment]
fuzzing is always fun :)
