### ISSUE TITLE
commit 2bc035c4b4384e460ffad7e9fa32b24918648e0d seems to have introduced a regression in jpeg decoding

### ISSUE THREAD

**Issue by gizmomogwai** [AuburnSounds/gamut#49]
I found an joeg in a jpeg testsuite, that works with version 2.1.1, but not with 2.1.2 or 2.1.3.
I uploaded the image to https://github.com/gizmomogwai/gamut/blob/main/examples/test-suite/test-images/316be81dfdeeb942e904feb3a77f4f83.jpg
When I run the decoder on it with newer versions I get just grey output, with 2.1.1 all is as expected.

**Comment by p0nce** [comment]
Interesting I have probably botched an optimization lately

**Comment by gizmomogwai** [comment]
I fear that was the jpeg non return refactoring as that's exactly the commit when it's starting for me ...

**Comment by gizmomogwai** [comment]
I fear that was the jpeg non return refactoring as that's exactly the commit when it's starting for me ...

**Comment by p0nce** [comment]
OK, the test is supposed to be a valid JPEG or invalid? In the latter case probably a missing decoding exit.

**Comment by p0nce** [comment]
OK so only the first 8192 bytes gets read, investigation just starting

**Comment by p0nce** [comment]
Progressive JPEG working again in v2.1.4

**Comment by gizmomogwai** [comment]
Thanks for this super quick fix! Works for me now as well!

**Comment by p0nce** [comment]
My pleasure! This was a dangerous regression
