### ISSUE TITLE
How do I save an array of pixels?

### ISSUE THREAD

**Issue by HuskyNator** [AuburnSounds/gamut#60]
I'm trying to save an array of pixels but can't seem to do so.
I can't access the pixel data directly (mutate it), can't seem to load pixel data directly (eg using `loadFromMemory`.
I tried using packed (gapless) data and `allPixelsAtOnce` on an initialized `Image`, but it only seems readable.

**Comment by p0nce** [comment]
What would have help you achieving this more readily?

**Comment by p0nce** [comment]
@HuskyNator perhaps there is a documentation issue we could fix?

**Comment by HuskyNator** [comment]
It'd be nice to be able to use loadFromMemory using a plain pixel array?
I feel like I'm hacking my way around this by using an assignment like `allPixelsAtOnce()[] = pixelsArray[]`.
Apart from that, it wasn't really clear whether this was possible from the docs. (Though I got it to work :) )

**Comment by p0nce** [comment]
Ah yes, `loadFromMemory()` is to load en encoded-image.
You are supposed to use `image.createViewFromData()` and then you have an Image which is a reference to that data (that you can .clone).

Maybe a new call that do that internally would be cool, please suggest a name maybe?

**Comment by HuskyNator** [comment]
Ah I see. I totally missed that comment! Totally my bad :)

In what way would the two be different?
I'd normally say making it doable using `loadFromMemory`, but that might be confusing/complex.
I think `loadFromPixels` or `loadFromPixelData` works well. :)

Also slightly confused about the existence of `LoadFlags` in this case.
They're not used by createViewFromData right? How do you implement the same change starting from pixel data?

Honestly quite confused about the difference between Layout, PixelFormat and LoadFlags.
They seem to overlap a bit?

**Comment by HuskyNator** [comment]
Seems I never noted this, but `loadFromPixels` is a good name.
