### ISSUE TITLE
can't setLayout twice

### ISSUE THREAD

**Issue by WebFreak001** [AuburnSounds/gamut#65]
my test code:

```d
import gamut;

void main()
{
	Image img;
	if (!img.loadFromFile("f6Mwgl.png", LOAD_FP32 | LOAD_GREYSCALE))
		throw new Exception(img.errorMessage().idup);
	if (!img.isValid)
		throw new Exception(img.errorMessage().idup);
	if (!img.setLayout(LAYOUT_TRAILING_1))
		throw new Exception(img.errorMessage().idup);
	// might be doing work here
	if (!img.setLayout(LAYOUT_TRAILING_0)) // <-- assert fails here
		throw new Exception(img.errorMessage().idup);
	if (!img.convertTo8Bit()) // <-- or here if the above setLayout isn't there
		throw new Exception(img.errorMessage().idup);
	if (!img.saveToFile("decoded.png")) // <-- this wouldn't assert fail, but it just emits an empty file with error set
		throw new Exception(img.errorMessage().idup);
}
```

the test file: https://wfr.moe/f6Mwgl.png

I would expect decoded.png to be practically the same as the input file (minus possible loss of precision)

Also is there a throwing API so I don't have to throw like this on every API call?

error:

```
core.exception.AssertError@/home/webfreak/.dub/packages/gamut/2.3.1/gamut/source/gamut/image.d(1767): Assertion failure
----------------
??:? _d_assertp [0x5562d1b35a1c]
/home/webfreak/.dub/packages/gamut/2.3.1/gamut/source/gamut/image.d:1767 nothrow @nogc @safe ushort gamut.image.Image.getAdHocLayoutConstraints() [0x5562d1adde6e]
/home/webfreak/.dub/packages/gamut/2.3.1/gamut/source/gamut/image.d:1145 nothrow @nogc @trusted bool gamut.image.Image.convertTo(gamut.types.PixelType, ushort) [0x5562d1adcde2]
/home/webfreak/.dub/packages/gamut/2.3.1/gamut/source/gamut/image.d:1048 nothrow @nogc @safe bool gamut.image.Image.setLayout(ushort) [0x5562d1adcb3c]
source/app.d:13 _Dmain [0x5562d1adae18]
Error Program exited with code 1
```

**Comment by WebFreak001** [comment]
when building without assertions, the image output seems to work fine, so just removing the assert(s) or better specifying them might be the solution?

**Comment by p0nce** [comment]
Please wait until tomorrow, I'm onto something else right now ^^

**Comment by p0nce** [comment]
Was a pretty real bug, nice catch. Would make things slower whan changing layout potentially.
Now fixed in v2.3.2

**Comment by p0nce** [comment]
> when building without assertions, the image output seems to work fine, so just removing the assert(s) or better specifying them might be the solution?

It was affecting "adhoc layout detection" : how the layout constraint can be deduced from pointers. So it would only affect performance not correctness.

**Comment by WebFreak001** [comment]
thanks for the quick fix!

**Comment by p0nce** [comment]
@WebFreak001 Need your input on this.

When you save an image, on failure (out of memory, disk error, unsupported format or extension, etc. then it returns false but you'll have no error message: doing that would clear the image).

What do you prefer:
1. Document current behaviour and say that saving error doesn't give an `.errorMessage` ?
2. Give an `.errorMessage` on saving error, but then clear the image state.

(If I give you both the error message AND the image stays intact, then it breaks the idea that "being valid" means "having no error message", and I heavily want to keep it that way.)

**Comment by WebFreak001** [comment]
I would personally prefer to have a throwing API (possibly separate from the nothrow API) - at least for high level operations

**Comment by p0nce** [comment]
What do you mean you want to double all the calls?

**Comment by p0nce** [comment]
No exceptions in WASM afaik.

**Comment by p0nce** [comment]
https://github.com/AuburnSounds/gamut/issues/66
