### ISSUE TITLE
Is this an issue (JPEG)

### ISSUE THREAD

**Issue by aferust** [AuburnSounds/gamut#71]
The left and right images are here.
https://slazebni.cs.illinois.edu/fall22/assignment3.html

When I try to open them using GIMP, it prompts a dialog saying this image has an embedded color profile, which is sRGB IEC61966-2.1. And GIMP offers a conversion.

The issue is gamut raises an assertion error when attempting to read those images:

\source\gamut\image.d(106): Assertion failure

**Comment by p0nce** [comment]
Hello,

Sorry for delay.
I don't manage to reproduce your issue, with any of the images.
![image](https://github.com/AuburnSounds/gamut/assets/1067485/34074c2e-c1be-4dec-9e7c-37c1caf92308)

Please provide a reproducible test case.

**Comment by aferust** [comment]
Ahh sory there is no any problem anymore. Although I don't know why.

**Comment by p0nce** [comment]
no problem!
